language: go

go:
  - 1.7
  - tip

os:
  - linux

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install: true

script:
  - go install
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then go test -v -covermode=count -coverprofile=profile.cov github.com/vpalmisano/svfs/svfs; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=svfs; fi'
